my_pddes/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from ui import views 

from knowledge_base.views import *
from inference_engine.views import *
from django.urls import path, include 



urlpatterns = [
    path('', views.home_view, name="homepage"), 
    path('about/', views.about_view), 
    path('register/', views.register_request, name="register"),
    path('help/', views.help_view), 
    path('contact/', views.contact_view), 
    path('admin/', admin.site.urls),
    path('test/',  d_test_view, name="test"),
    path('ghq/', ghq_view, name="ghq"),
    path('anxiety_test/', anxiety_page_view),
    path('sa_anxiety_test/', socialanxiety_page_view),
    path('depression_test/', depression_page_view),
    path('ocd_test/', ocd_view),
    path('antisocial_test/', antisocial_view),
    path('ptsd_test/', ptsd_page_view),
    path('bipolar_test/', bipolar_view),
    #bipolar is left 
    


    path('results/', results_view, name="results"),   
    path('accounts/login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('expert_ui/', views.expert_ui_view, name="expert_ui"),
    path('normal_dash/', views.normal_dashboard_view,name="normal_dash"), 
    

    
    path('password_reset/', views.password_reset_view, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password-related/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password-related/confirm_password.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password-related/complete_pw_reset.html'), name='password_reset_complete'),      
    #path("accounts/", include("django.contrib.auth.urls")),
    # kb stuff
    path("kb-interface/<int:id>", disorder_info_view, name="kb-interface"),
    path('get_disorder_info/', get_disorder_info, name='get_disorder_info'),
]

ui/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.contrib import admin


# Create your models here.


class Question(models.Model):

    question_text = models.TextField()
    
    # add a field for the choices
    
    def __str__(self):
        return self.question_text
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
   

    def __str__(self):
        return self.choice_text

templates/Screening_pgs/diagnosis_test.html
{% extends 'base.html' %}


<head>
  
</head>

{% block content %}

{% load static %}

{% load crispy_forms_tags %} 

<br>
<h2> Questions </h2>

<fieldset>
  <form method="POST">

    {% csrf_token %}
    <div id="questions-container">
      <br> 
        {{ questions_form|crispy}}
    </div>
    <br>
    <div id="buttons-container">
      <!--
      <button type="button" id="back-button" disabled>Back</button>
      <button type="button" id="next-button">Next</button> -->
      
      <button type="submit" id="submit-button" >Submit</button>
    </div>
    
  </form>
 <br>
  
  
</fieldset>



<style>
  body {
    font-family: Arial, sans-serif;
    font-size: 16px;
  }
  
  h2 {
    margin-top: 20px;
    margin-bottom: 20px;
  }
  
  fieldset {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  #questions-container {
    margin-bottom: 20px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  label {
    font-weight: bold;
  }
  
  input[type="radio"] {
    margin-right: 10px;
  }
  
  #buttons-container {
    text-align: right;
    margin-top: 20px;
  }
  
  #prev-button {
    margin-right: 10px;
  }
  
  button {
    font-size: 16px;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    background-color: #007bff;
    color: #fff;
    cursor: pointer;
  }
  
  button:hover {
    background-color: #0069d9;
  }
  
  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
</style>
    
<script>

var questions = document.getElementsByClassName('question-container');
    var currentQuestion = 0;
    var backButton = document.getElementById('back-button');
    var nextButton = document.getElementById('next-button');
    var submitButton = document.getElementById('submit-button');

    function showQuestion(index) {
      for (var i = 0; i < questions.length; i++) {
        questions[i].style.display = 'none';
      }
      questions[index].style.display = 'block';

      currentQuestion = index;

      if (currentQuestion === 0) {
        backButton.disabled = true;
      } else {
        backButton.disabled = false;
      }

      if (currentQuestion === questions.length - 1) {
        nextButton.style.display = 'none';
        submitButton.style.display = 'block';
      } else {
        nextButton.style.display = 'block';
        submitButton.style.display = 'none';
      }
    }

    showQuestion(currentQuestion);

    backButton.addEventListener('click', function() {
      showQuestion(currentQuestion - 1);
    });

    nextButton.addEventListener('click', function() {
      showQuestion(currentQuestion + 1);
    });

 
</script>

{% endblock %}

<!--
  <form method="POST" id="quiz-form">
    {% csrf_token %}
    <div id="questions-container">
      {% for question in questions %}
        <div class="question-container" id="question-{{ question.id }}">
          <br> <br> 
          <h3>{{ question.question_text }}</h3>
          <ul style="list-style-type:none;" >
            {% for choice in question.choice_set.all %}
              <li>
                <label>
                  <input type="radio" name="{{ question.id }}" value="{{ choice.id }}">
                  {{ choice.choice_text }}
                </label>
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endfor %}
    </div>
      -->

templates/Screening_pgs/ghq.html
{% extends "base.html" %}


{% block content %}



{% load crispy_forms_tags %} 

<center> <h2> General screening  </h2> </center>

<br>

  <div class="form_stuff">
      <form method="POST">
    {% csrf_token %}

    <div class="ghq12">
        {{gen_questions.as_p}}

    </div>
    <div id="buttons-container">
      <!--
      <button type="button" id="back-button" disabled>Back</button>
      <button type="button" id="next-button">Next</button> -->
      
      <button type="submit" id="submit-button" data-bs-target="#reg-modal">Submit</button>
    </div>

  

</form>
  </div>



<style>
     body {
    font-family: Arial, sans-serif;
    font-size: 16px;
  }
  
  .form_stuff {
  border: 1px solid #ccc;
  border-radius: 12px;
  padding: 20px;
  max-width: 600px;
  margin: 0 auto;
}
  h2 {
    margin-top: 20px;
    margin-bottom: 20px;
  }
  
  fieldset {
    border: 1px solid #ccc;
    padding: 20px;
  }
  
  #questions-container {
    margin-bottom: 20px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  label {
    font-weight: bold;
  }
  
  input[type="radio"] {
    margin-right: 10px;
  }
  
  #buttons-container {
    text-align: right;
    margin-top: 20px;
  }
  
  #prev-button {
    margin-right: 10px;
  }
  
  button {
    font-size: 16px;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    background-color: #007bff;
    color: #fff;
    cursor: pointer;
  }
  
  button:hover {
    background-color: #0069d9;
  }
  
  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
</style>
    
</style>


{% endblock %}

templates/Screening_pgs/ghq_result.html
{% extends "base.html" %}


{% block content %}



{% load crispy_forms_tags %} 

<br>
<h2> General Assessment Results</h2>
<br>

<div class="result">

   <h3> {{message}} </h3>
    <br> <br>
    <h3> Test score: {{score}}</h3>
    <br>

    <h3> How the score is calculated?</h3>
    <br> 
    <p> In case you're interested in knowing how the score is calculated: </p>
    <p>
        each response option is assigned a score of 0, 1, 2, or 3. 
        The score assigned to each option typically reflects the level of 
        distress or impairment reported by the respondent. 
        The specific scoring values may vary slightly depending on the 
        scoring method used, but the most commonly used values are as follows:
    </p>
    <br> 
    <p>
        0 - Better than usual
        1 - No more than usual
        2 - Rather more than usual
        3 - Much more than usual

        For example, for question 1 ("Have you recently felt constantly under strain?"), if the respondent answers "Better than usual," they would be assigned a score of 0. If they answer "No more than usual," they would be assigned a score of 1. If they answer "Rather more than usual," they would be assigned a score of 2. And if they answer "Much more than usual," they would be assigned a score of 3.
    </p>
    <br>
    <p>
        The other 11 questions would be scored similarly, with each response receiving a score of 0, 1, 2, or 3. A total score is generated when all 12 items have been scored, and it can vary from 0 to 36. Higher scores indicate greater levels of psychological distress or disability.
    </p>
</div>

<style>
    *{
        color:white;
    }
    .result {
        padding: 20px;
        
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-top: 20px;
    }

    h3 {
        font-size: 23px;
        margin-top: 20px;
        margin-bottom: 10px;
    }
    h2 {
        margin-top: 20px;
        margin-bottom: 10px;
    }
</style>


{% endblock %}

templates/Screening_pgs/new_results.html
{% extends 'base.html' %}


{% block content %}

<br>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <script>
   const myModal = new boostrap.Modal('#gps-modal');
   
   window.addEventListener('DOMContentLoaded', () => {
    myModal.show();
   });


  </script>
</head>
<center><h2> Test Results <i class="bi bi-file-check-fill"></i> </h2></center>
<br>



<div class="results-container">
  
    {% if score >= 10 %}
      <div class="likelihood_score">

     
        <h3> The results show that you are most probably suffering from {{description.disorder_name}}, 
        </h3>
        <br>
        <h3> Likelihood: {{likelihood}}</h3>
        <br>
        <!--Would you like to allow the system to display nearby clinics on a map?-->
       
        <div class="modal" tabindex="-1" role="dialog" id="gps-modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">GPS access toggle </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p id="modal-p">Would you like to allow the system to display nearby clinics on a map?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-success" id="allow-btn">Allow</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Deny</button>
              </div>
            </div>
          </div>
        </div>
        
        <script>
          const dialog = document.getElementById('gps-modal');
          const allowBtn = document.getElementById('allow-btn');
          const denyBtn = document.querySelector('.modal-footer .btn-danger');
        
          function showMapDialog() {
            dialog.style.display = 'block';
          }
        
          function hideMapDialog() {
            dialog.style.display = 'none';
          }
        
          function allowMap() {
            navigator.geolocation.getCurrentPosition((position) => {
              const latitude = position.coords.latitude;
              const longitude = position.coords.longitude;
              const searchTerm = "Mental Clinics";
              const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(searchTerm)}&center=${latitude},${longitude}&zoom=15`;
              //const mapUrl = `https://www.google.com/maps/@${latitude},${longitude},15z`;
              window.open(mapUrl, '_blank');
            });
            hideMapDialog();
          }
        
          function denyMap() {
            hideMapDialog();
          }
        
          allowBtn.addEventListener('click', allowMap);
          denyBtn.addEventListener('click', denyMap);
        </script>
 <script>
    showMapDialog();
 </script>
        <h3> Score: {{score}}</h3>
      </div>
        <br>
       <div class="desc">
        <h3>Description: <i class="bi bi-info-circle-fill"></i> </h3>
        <br>
        <p> {{description.disorder_desc}}</p>
      </div>
        <br> 
        <div class="recommend">
        <h3>Recommendation <i class="bi bi-check-circle-fill"></i> </h3>
        <br>
        <p> {{description.recommendation}}</p>
      </div>

    {% elif score >= 5 %}
      <div class="likelihood_score">
        <h3> The results show that it is possible that you are suffering from {{description.disorder_name}}, your case is not severe
        </h3>
        <br>
        <h3> Likelihood: {{likelihood}}</h3>
        <h3> Score: {{score}}</h3>
      </div>
      <br>

        <div class="desc">
          <h3>Description: <i class="bi bi-info-circle-fill"></i> </h3>
          <br>
          <p> {{description.disorder_desc}}</p>
        </div>
      
        <br>
        <div class="recommend">
          <h3>Recommendation <i class="bi bi-check-circle-fill"></i> </h3>
          <br>
          <p> {{description.recommendation}}</p>
        </div> 
       
    {% else %}
    <h3> The results show that it is unlikely that you are suffering from {{description.disorder_name}} </h3>
    <h3> Score: {{score}}</h3>
        
    {% endif %}
    <br> 
    
        
 


</div>
<style>
   h3, h2, h1, p   {
    color:white;
   }
   #modal-p {
    color:black;
   }
   .modal-content {
    background:darkgray;
   }
    #dialog {
        margin: auto;
        width: 50%;
        padding: 10px;
        border: solid white  5px;
    }
    #allow-btn {
      font-size: 16px;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      background-color: #4400ff;
      color: #fff;
      cursor: pointer;
      align-items: center;
    }
    #deny-btn {
      font-size: 16px;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      background-color: red;
      color: #fff;
      cursor: pointer;
      align-items: center;
    }
    .likelihood_score, .desc, .recommend {
      border: 1px solid #ccc;
      border-radius: 12px;
      padding: 20px;
      max-width: 600px;
      margin: 0 auto;
     /* background-color: ; */
    }
</style>




{% endblock %}

templates/Screening_pgs/prediction_result.html
{% extends 'base.html' %}


{% block content %}
<head>
  <title>Prediction Results</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- jQuery library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GcyfP9ll8ik6W5OcQCukw6/ff1QIl5rZjYiAKA5l6FX5C9N4yM3fSAv4RRpGKxjx4S06HITRZY/WfmKjLEL31Q==" crossorigin="anonymous" referrerpolicy="no-referrer" /> <!-- Bootstrap CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-09s7s+20YsTHf7/F0dSiXK1f3q4H+GNpLJjkrxNlS8Z/ud+oRjJZ6BoE2QikrqW6R9jjCY5J5PQjID7V4J4GEw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> <!-- Bootstrap JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha384-g6ISQ28dLlS6GQezbqJFAq5gM/QdM5mrb17F8/kCJpBPL+PBlkSYflW7R8tJpRZ+" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha384-WM1QTZBxjEIQsV7T8/dwLcV7ymDLeJe03kf7W8Lk/ET1QGGZHYHeBMGm7V8BwDJu" crossorigin=""></script>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>

<br> 


<!-- Include the description of the disorder and add recommendations-->
<!-- Add a container for the results -->
<div class="results-container">

    {% if social_anxiety %}
      <h2 class="result-title">Results</h2>
      <h3>You may have social anxiety.</h3>
      <h3>Likelihood: {{likelihood}}</h3>
      <p></p>
      <h2 class="desc-title">Disorder Description</h2>
      <p>{{sa_desc.disorder_desc}}</p>
      <h2 class="recommendation-title">Recommendations</h2>
      <p>{{sa_desc.recommendation}}</p>
    {% endif %}
  
    {% if anxiety %}
      <h2 class="result-title">Results</h2>
      <h3>You may have generalized anxiety disorder.</h3>
      <h3>Likelihood: {{likelihood}}</h3>
      <p></p>
      <h2 class="desc-title">Disorder Description</h2>
      <p>{{aa_desc.disorder_desc}}</p>
      <h2 class="recommendation-title">Recommendations</h2>
      <p>{{aa_desc.recommendation}}</p>
    {% endif %}
  
 


{% if ptsd %}

<h2>Results</h2> <br>

<h3>You may have post traumatic stress disorder .</h3>
 <h3> Likelihood:   {{likelihood}}</h3>
<p> </p>

<br> <br>
<h2> Disorder Description </h2>
<p> {{ptsd_desc.disorder_desc}} </p>
<br> <br>
    <h2> Recommendations</h2> <br>
    <p> {{ptsd_desc.recommendation}}</p>

{% endif %}

{% if ocd %}
 
<h2>Results</h2> <br>



<h3>You may have obsessive compulsive disorder .</h3> <br> 
 <h3> Likelihood:   {{likelihood}}</h3>
 {% if likelihood == "Highly Likely"%}

 <div id="dialog" style="display:none">
  <p>Would you like to allow the system to display nearby clinics on a map?</p>
  <button id="allow-btn">Allow</button>
  <button id="deny-btn">Deny</button>
 </div>
  
    <script>
    const dialog = document.getElementById('dialog');
    const allowBtn = document.getElementById('allow-btn');
    const denyBtn = document.getElementById('deny-btn');

    function showMapDialog() {
      dialog.style.display = 'block';
    }

    function hideMapDialog() {
      dialog.style.display = 'none';
    }

    function allowMap() {
      navigator.geolocation.getCurrentPosition((position) => {
        const latitude = position.coords.latitude;
        const longitude = position.coords.longitude;
        const searchTerm = "Mental Clinics"
        const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(searchTerm)}&center=${latitude},${longitude}&zoom=15`;
        //const mapUrl = `https://www.google.com/maps/@${latitude},${longitude},15z`;
        window.open(mapUrl, '_blank');
      });
      hideMapDialog();
    }

    function denyMap() {
      hideMapDialog();
    }

    allowBtn.addEventListener('click', allowMap);
    denyBtn.addEventListener('click', denyMap);

    </script>
 <script>
    showMapDialog();
 </script>
 <style>
  button{
    color:black;
 
  }
  #dialog{
  display: flex;
  justify-content: center; /* centers items horizontally */
  align-items: center; /* centers items vertically */
  height: 100%;
  margin: auto;
  width: 50%;
  border: solid white ;
}

 </style>
 {% endif %}
<p> </p>
<br> <br>
<h2> Disorder Description </h2>
<p> {{ocd_desc.disorder_desc}}</p>
<br> <br>
    <h2> Recommendations</h2>
<br>
<p>{{ocd_desc.recommendation}}</p>



{% endif %}



{% if anti_social %}

<h2>Results</h2> <br>

<h3>You may have anti-social personality disorder .</h3>
<br> <br> 

 <h3> Likelihood:   {{likelihood}}</h3>
<p> </p>


<br> <br>
<h2> Disorder Description </h2>
<br>
<p> {{anti_social_desc.disorder_desc}}</p>

<br> <br>
    <h2> Recommendations</h2><br>
<p> {{anti_social_desc.recommendation}}</p>

{% endif %}

{% if depression %}

<h2>Results</h2> <br>

<h3>You may have depression .</h3>

<br> <br> 

 <h3> Likelihood:   {{likelihood}}</h3>
<p> </p>

<br> <br>
<h2> Disorder Description </h2>

<br>
<p>{{depression_desc.disorder_desc}}</p>
<br>
    <h2> Recommendations</h2>
    <br>
    <p>{{depression_desc.recommendation}}</p>
{% endif %}


{% if bipolar %}

<h2>Results</h2> <br>

<h3>You may have bipolar disorder .</h3>

<br> <br> 

 <h3> Likelihood:   {{likelihood}}</h3>
<p> </p>

<br> <br>
<h2> Disorder Description </h2>
<p>{{bipolar_desc.disorder_desc}}</p>


<br> <br>
    <h2> Recommendations</h2>
{% endif %}
</div>
<style>
    .results-container {
  padding: 20px;
 
  border-radius: 5px;
  margin-top: 20px;
}

.result-title {
  font-size: 28px;
  margin-bottom: 10px;
}

.desc-title, .recommendation-title {
  font-size: 24px;
  margin-top: 20px;
  margin-bottom: 10px;
}

</style>

{% endblock %}